# Generated by Django 4.2.1 on 2023-09-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twofactortoken',
            old_name='totp_key',
            new_name='totp',
        ),
    ]
