# Generated by Django 4.2.1 on 2023-09-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0002_rename_totp_key_twofactortoken_totp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twofactortoken',
            old_name='last_verified_otp',
            new_name='last_verified_otp_key',
        ),
        migrations.RenameField(
            model_name='twofactortoken',
            old_name='totp',
            new_name='totp_key',
        ),
    ]
