# Generated by Django 4.2.1 on 2023-09-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0003_rename_last_verified_otp_twofactortoken_last_verified_otp_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twofactortoken',
            old_name='last_verified_otp_key',
            new_name='last_verified_otp',
        ),
    ]
