# Generated by Django 4.2.1 on 2023-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0006_alter_twofactortoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactortoken',
            name='backup_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twofactortoken',
            name='date_2fa_enabled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twofactortoken',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twofactortoken',
            name='has_enabled_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
