# Generated by Django 4.2.1 on 2023-09-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0007_twofactortoken_backup_codes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactortoken',
            name='failed_attempts',
        ),
    ]
