# Generated by Django 4.2.1 on 2023-09-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0010_alter_twofactortoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactortoken',
            name='backup_codes',
        ),
        migrations.RemoveField(
            model_name='twofactortoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='twofactortoken',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='twofactortoken',
            name='updated_at',
        ),
    ]
