# Generated by Django 4.2.1 on 2023-09-18 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0011_remove_twofactortoken_backup_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactortoken',
            name='backup_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twofactortoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 18, 4, 57, 50, 726466, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twofactortoken',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twofactortoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
