# Generated by Django 4.2.1 on 2023-09-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0012_twofactortoken_backup_codes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twofactortoken',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
