# Generated by Django 4.2.1 on 2023-09-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0013_rename_updated_at_twofactortoken_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twofactortoken',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
