# Generated by Django 4.2.1 on 2023-09-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0014_rename_created_at_twofactortoken_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactortoken',
            name='date_2fa_disabled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
