# Generated by Django 4.2.1 on 2023-09-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0015_twofactortoken_date_2fa_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactortoken',
            name='has_enabled_2fa',
        ),
    ]
