# Generated by Django 4.2.1 on 2023-09-18 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0018_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 6, 27, 6, 841158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp',
            field=models.CharField(max_length=8),
        ),
    ]
