# Generated by Django 4.2.1 on 2023-09-18 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0019_alter_otpverification_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverification',
            old_name='otp',
            new_name='otp_code',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 6, 27, 33, 648082, tzinfo=datetime.timezone.utc)),
        ),
    ]
