# Generated by Django 4.2.1 on 2023-09-18 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_authentication', '0020_rename_otp_otpverification_otp_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverification',
            old_name='otp_code',
            new_name='otp',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 6, 27, 47, 687855, tzinfo=datetime.timezone.utc)),
        ),
    ]
