# Generated by Django 4.2.1 on 2023-08-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_rename_follower_profile_follower_count_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_logged_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
