# Generated by Django 4.2.1 on 2023-09-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_alter_follow_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
