# Generated by Django 4.2.1 on 2023-09-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_profile_following_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='followers',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followers', 'followed')},
        ),
    ]
