# Generated by Django 4.2.1 on 2023-09-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_rename_followed_follow_followed_people_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followed_people',
            new_name='followed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed')},
        ),
    ]
