# Generated by Django 4.2.1 on 2023-09-16 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_logindetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 16, 3, 43, 14, 412706, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
