# Generated by Django 4.2.1 on 2023-09-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_logindetail_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindetail',
            old_name='timestamp',
            new_name='login_date',
        ),
    ]
