# Generated by Django 4.2.1 on 2023-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_rename_timestamp_logindetail_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetail',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
