# Generated by Django 4.2.1 on 2023-09-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_logindetail_is_read'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed', 'date_followed')},
        ),
    ]
