# Generated by Django 4.2.1 on 2023-09-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0023_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed')},
        ),
    ]
