# Generated by Django 4.2.1 on 2023-09-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0024_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_enabled_verification',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
