# Generated by Django 4.2.1 on 2023-09-18 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_profile_has_enabled_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_enabled_verification',
            new_name='enabled_verification',
        ),
    ]
