# Generated by Django 4.2.1 on 2023-09-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_rename_has_enabled_verification_profile_enabled_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
