# Generated by Django 4.2.1 on 2023-09-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_remove_profile_verification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='enabled_verification',
        ),
    ]
