# Generated by Django 4.2.1 on 2023-08-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_blogpost_likes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='post_content',
        ),
    ]
