# Generated by Django 4.2.1 on 2023-08-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_rename_content_blogpost_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_content',
            new_name='content',
        ),
    ]
