# Generated by Django 4.2.1 on 2023-08-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_blogcomment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='reply',
            new_name='comment_reply',
        ),
    ]
