# Generated by Django 4.2.1 on 2023-08-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_rename_reply_blogcomment_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='comment_reply',
        ),
    ]
