# Generated by Django 4.2.1 on 2023-09-06 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0020_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageApp',
        ),
    ]
