# Generated by Django 4.2.1 on 2023-09-07 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0021_alter_message_file_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 7, 4, 16, 30, 950817, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
