# Generated by Django 4.2.1 on 2023-09-07 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_chatroom_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 7, 4, 17, 12, 356201, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
