# Generated by Django 4.2.1 on 2023-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_messageapp_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageapp',
            name='message',
            field=models.TextField(),
        ),
    ]
