# Generated by Django 4.2.1 on 2023-09-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0023_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
