# Generated by Django 4.2.1 on 2023-09-06 07:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0023_alter_messageapp_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageapp',
            name='user',
        ),
        migrations.AddField(
            model_name='messageapp',
            name='receiver',
            field=models.ForeignKey(default=datetime.datetime(2023, 9, 6, 7, 5, 3, 265054, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='receiving_person', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageapp',
            name='sender',
            field=models.ForeignKey(default=datetime.datetime(2023, 9, 6, 7, 5, 22, 841578, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, related_name='sending_person', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
