# Generated by Django 4.2.1 on 2023-09-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0024_blogpost_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
