# Generated by Django 4.2.1 on 2023-09-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_notification_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
