# Generated by Django 4.2.1 on 2023-09-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0026_alter_notification_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='count',
            new_name='unread_count',
        ),
    ]
